# Generated by Django 3.2.25 on 2025-01-31 21:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer')),
                ('question_hi', models.TextField(blank=True, null=True, verbose_name='Question (Hindi)')),
                ('answer_hi', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer (Hindi)')),
                ('question_en', models.TextField(blank=True, null=True, verbose_name='Question (English)')),
                ('answer_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer (English)')),
            ],
        ),
    ]
